from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[2]
if REPO_ROOT.as_posix() not in sys.path:
    sys.path.insert(0, REPO_ROOT.as_posix())

from data.exporters.bagel import export_bagel  # noqa: E402
from data.scan import build_samples_from_data_root, write_manifest  # noqa: E402


TASK_GROUP_CHOICES = ("eyeballing", "maze", "visual_puzzle")


def normalize_task_groups(task_groups: Sequence[str] | None) -> list[str]:
    if not task_groups:
        return list(TASK_GROUP_CHOICES)
    normalized = []
    for task_group in task_groups:
        task_group_clean = str(task_group).strip()
        if task_group_clean not in TASK_GROUP_CHOICES:
            raise ValueError(f"Unsupported task group: {task_group_clean}")
        normalized.append(task_group_clean)
    return normalized


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare BAGEL training data from a VideoThinkBench data root.")
    parser.add_argument("--dataset_root", required=True, help="Root generated by cli.py data generate.")
    parser.add_argument("--output_dir", required=True, help="BAGEL export output directory.")
    parser.add_argument(
        "--task_groups",
        nargs="+",
        default=list(TASK_GROUP_CHOICES),
        choices=list(TASK_GROUP_CHOICES),
        help="Task groups to scan before exporting.",
    )
    parser.add_argument("--modes", default="edit,vlm", help="Comma-separated BAGEL export modes: edit, vlm.")
    parser.add_argument("--parquet_rows_per_file", type=int, default=1024, help="Rows per BAGEL edit parquet shard.")
    parser.add_argument("--manifest_path", default=None, help="Optional canonical manifest output path.")
    args = parser.parse_args()

    dataset_root = Path(args.dataset_root).expanduser().resolve()
    if not dataset_root.is_dir():
        raise FileNotFoundError(f"Dataset root does not exist: {dataset_root}")
    task_groups = normalize_task_groups(args.task_groups)
    samples = build_samples_from_data_root(dataset_root, task_groups=task_groups)

    output_dir = Path(args.output_dir).expanduser().resolve()
    modes = [part.strip() for part in str(args.modes).split(",") if part.strip()]
    outputs = export_bagel(
        samples,
        output_dir=output_dir,
        modes=modes,
        task_groups=task_groups,
        parquet_rows_per_file=args.parquet_rows_per_file,
    )

    manifest_path = None
    if args.manifest_path:
        manifest_path = Path(args.manifest_path).expanduser().resolve()
        write_manifest(manifest_path, samples)

    print("============================================================")
    print("BAGEL training data prepared")
    print(f"Dataset root: {dataset_root}")
    print(f"Scanned samples: {len(samples)}")
    print(f"Modes: {', '.join(modes)}")
    print(f"Output dir: {output_dir}")
    for name, path in sorted(outputs.items()):
        print(f"{name}: {path}")
    if manifest_path is not None:
        print(f"Manifest: {manifest_path}")
    print("============================================================")


if __name__ == "__main__":
    main()
