from __future__ import annotations

import argparse
from pathlib import Path

from _prepare_training_data_common import TASK_GROUP_CHOICES, load_samples, maybe_write_manifest
from data.exporters.ms_swift import export_ms_swift


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prepare ms-swift JSONL files from a VideoThinkBench data root.",
    )
    parser.add_argument("--data_root", default=None, help="Root generated by cli.py data generate.")
    parser.add_argument("--dataset_root", default=None, help="Alias of --data_root.")
    parser.add_argument("--output_dir", required=True, help="Output directory for train_sft.jsonl and train_grpo.jsonl.")
    parser.add_argument(
        "--task_groups",
        nargs="+",
        default=list(TASK_GROUP_CHOICES),
        choices=list(TASK_GROUP_CHOICES),
        help="Task groups to scan before exporting.",
    )
    parser.add_argument(
        "--modes",
        default="sft,grpo",
        help="Comma-separated export modes. Supported values: sft,grpo.",
    )
    parser.add_argument(
        "--manifest_path",
        default=None,
        help="Optional canonical manifest output path for the scanned samples.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    data_root = args.data_root or args.dataset_root
    if not data_root:
        raise SystemExit("One of --data_root or --dataset_root is required.")

    dataset_root, task_groups, samples = load_samples(data_root, args.task_groups)
    output_dir = Path(args.output_dir).expanduser().resolve()
    modes = [part.strip() for part in args.modes.split(",") if part.strip()]
    outputs = export_ms_swift(samples, output_dir=output_dir, modes=modes, task_groups=task_groups)
    manifest_path = maybe_write_manifest(args.manifest_path, samples)

    allowed_groups = set(task_groups)
    exportable_count = sum(1 for sample in samples if sample.task_group in allowed_groups)
    print("============================================================")
    print("VLM training data prepared")
    print(f"Dataset root: {dataset_root}")
    print(f"Scanned samples: {len(samples)}")
    print(f"Exported rows: {exportable_count}")
    for output in outputs:
        print(f"Output: {output}")
    if manifest_path is not None:
        print(f"Manifest: {manifest_path}")
    print("============================================================")


if __name__ == "__main__":
    main()
