from __future__ import annotations

import argparse
from pathlib import Path

from _prepare_training_data_common import TASK_GROUP_CHOICES, load_samples, maybe_write_manifest
from data.exporters.diffsynth_image import export_diffsynth_image


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prepare DiffSynth image metadata from a VideoThinkBench data root.",
    )
    parser.add_argument("--dataset_root", required=True, help="Root generated by cli.py data generate.")
    parser.add_argument("--output_path", required=True, help="JSON metadata output path.")
    parser.add_argument(
        "--task_groups",
        nargs="+",
        default=list(TASK_GROUP_CHOICES),
        choices=list(TASK_GROUP_CHOICES),
        help="Task groups to scan before exporting.",
    )
    parser.add_argument(
        "--manifest_path",
        default=None,
        help="Optional canonical manifest output path for the scanned samples.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    dataset_root, task_groups, samples = load_samples(args.dataset_root, args.task_groups)
    output_path = Path(args.output_path).expanduser().resolve()
    export_diffsynth_image(samples, output_path=output_path, task_groups=task_groups)
    manifest_path = maybe_write_manifest(args.manifest_path, samples)

    allowed_groups = set(task_groups)
    exportable_count = sum(1 for sample in samples if sample.task_group in allowed_groups)
    print("============================================================")
    print("Image training data prepared")
    print(f"Dataset root: {dataset_root}")
    print(f"Scanned samples: {len(samples)}")
    print(f"Exported rows: {exportable_count}")
    print(f"Metadata: {output_path}")
    if manifest_path is not None:
        print(f"Manifest: {manifest_path}")
    print("============================================================")


if __name__ == "__main__":
    main()
